import * as React from 'react'
import './globals.css'
import { font } from './fonts'
import { cn } from '@/lib/utils'
import Providers from '@/providers'

export const metadata = {
  title: 'EL Butique App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cn('', font.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
